require 'typescript/monkey'
require 'typescript/monkey/configuration'
require 'typescript/monkey/railtie'
require 'typescript/monkey/engine'
require 'typescript/monkey/template'
require 'typescript/monkey/template_handler'
require 'typescript/monkey/transformer'
require 'typescript/monkey/transpiler'
